# Generated by Django 3.1.7 on 2021-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='pic',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
