# Generated by Django 3.1.7 on 2021-03-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210313_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='audios'),
        ),
        migrations.AlterField(
            model_name='song',
            name='pic',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
